# Generated by Django 3.2.4 on 2022-12-30 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0003_customuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='auth.group'),
        ),
    ]
