# Generated by Django 4.1.2 on 2022-12-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_customuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
    ]
